@server = https://smart.argo.run/v/r4/sim/test/fhir
@subject = Patient/123
@stateCodingSystem = https://demo-app.example.org
@stateCodingCode = user-preferences
@extensionUrl = https://demo-app.example.org/favorite-color

###
# Create favorite color as burlywood
POST {{server}}/$smart-app-state-modify
Content-Type: application/fhir+json

{
    "resourceType":"Basic",
    "subject":{"reference":"{{subject}}"},
    "code":{
      "coding":[{
        "system":"{{stateCodingSystem}}",
        "code":"{{stateCodingCode}}"}
    ]},
    "extension":[{
        "url":"{{extensionUrl}}",
        "valueString":"burlywood"
    }]
}

###
# Query favorite color
// @name queryAppState
GET https://smart.argo.run/v/r4/sim/test/fhir/$smart-app-state-query
    ?subject={{subject}}
    &code={{stateCodingSystem}}|{{stateCodingCode}}

@firstAppStateId = {{queryAppState.response.body.entry[0].resource.id}}
@firstAppStateVid = {{queryAppState.response.body.entry[0].resource.meta.versionId}}

###
# Change favorite color to aquamarine

POST https://smart.argo.run/v/r4/sim/test/fhir/$smart-app-state-modify
Content-Type: application/fhir+json
If-Match: W/"{{firstAppStateVid}}"

{
    "resourceType":"Basic",
    "id": "{{firstAppStateId}}",
    "subject":{"reference":"{{subject}}"},
    "code":{
      "coding":[{
        "system":"{{stateCodingSystem}}",
        "code":"{{stateCodingCode}}"}
    ]},
    "extension":[{
        "url":"{{extensionUrl}}",
        "valueString":"aquamarine"
    }]
}


###
# Delete favorite color

POST https://smart.argo.run/v/r4/sim/test/fhir/$smart-app-state-modify
Content-Type: application/fhir+json
If-Match: W/"{{firstAppStateVid}}"

{
    "resourceType":"Basic",
    "id": "{{firstAppStateId}}",
    "subject":{"reference":"{{subject}}"},
    "code":{
      "coding":[{
        "system":"{{stateCodingSystem}}",
        "code":"{{stateCodingCode}}"}
    ]}
}
